### ISSUE TITLE
Issue with editing datasets with selected geographies

### ISSUE THREAD

**Issue by apoorv74** [justicehub-in/ckanext-justicehub_theme#83] opened 2021-02-23 07:33 UTC
Couple of issues related to selecting and updating geographies:

1 - when we edit a dataset, the geography list is not updated in case we have selected certain geographies
2 - Not able to select Delhi as one of the geographies.

Check this dataset for sample - https://justicehub.in/dataset/satarc-a-household-survey-in-four-major-indian-cities

**Comment by akkisagiraju** [comment] 2021-02-23 08:12
This is now fixed.

**Comment by akkisagiraju** [comment] 2021-02-24 20:17
Found out the cause for not being able to select some regions.

There's old code that was replacing the latest states list we've added in the HTML. So, even though the recently added states show up as options, they weren't really present. Fixed this issue.

**Comment by akkisagiraju** [comment] 2021-02-25 04:56
Looking in to the issue where you have to manually re-select all the existing states in edit flow.

**Comment by akkisagiraju** [comment] 2021-03-10 07:41
The linked PR fixes the issue in edit mode where you have to manually re-select the existing states of a dataset.

**Closed** 2021-03-10 17:21 UTC
Labels: bug
